/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, IPropagation, Resolved } from "@nestia/fetcher";
import typia from "typia";
export * as user from "./user";
/**
 * @controller AppController.getHello
 * @path GET /:param
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getHello(connection: IConnection, param: string): Promise<getHello.Output>;
export declare namespace getHello {
    type Output = IPropagation<{
        200: string;
    }>;
    const METADATA: {
        readonly method: "GET";
        readonly path: "/:param";
        readonly request: null;
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: null;
    };
    const path: (param: string) => string;
    const random: (g?: Partial<typia.IRandomGenerator>) => Resolved<string>;
    const simulate: (connection: IConnection, param: string) => Output;
}
